# Gemfile

source 'https://rubygems.org'

gem "jekyll", "~> 3.10"

group :jekyll_plugins do
  gem "jekyll-timeago", "~> 0.13.1"
  gem "jekyll-github-metadata"
end

gem "jekyll-remote-theme"

gem 'github-pages', '~> 232'

gemspec
